documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
    - any-glob-to-any-file: 'docs/**/*'

tests:
  - changed-files:
    - any-glob-to-any-file: 'tests/**/*'

source-generator:
  - changed-files:
    - any-glob-to-any-file: 'src/PotternMotching.SourceGen/**/*'

matchers:
  - changed-files:
    - any-glob-to-any-file: 'src/PotternMotching/Matchers/**/*'

patterns:
  - changed-files:
    - any-glob-to-any-file: 'src/PotternMotching/Patterns/**/*'

samples:
  - changed-files:
    - any-glob-to-any-file: 'samples/**/*'

ci/cd:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'
