namespace PotternMotching.SourceGen;

using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using PotternMotching.SourceGen.Models;

internal static class PatternCodeGenerator
{
    public static string Generate(TypeAnalysisResult analysis)
    {
        if (analysis.IsUnion)
        {
            return GenerateUnionPattern(analysis);
        }

        var typeSymbol = analysis.TypeSymbol;
        var typeName = typeSymbol.Name;
        var patternName = $"{typeName}Pattern";
        var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
        var isGlobalNamespace = typeSymbol.ContainingNamespace.IsGlobalNamespace;

        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using PotternMotching;");
        sb.AppendLine("using PotternMotching.Patterns;");
        sb.AppendLine();

        // Namespace (only if not global)
        if (!isGlobalNamespace)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        // Class declaration
        sb.Append($"public sealed record {patternName}(");

        // Parameters
        if (analysis.Properties.Length > 0)
        {
            sb.AppendLine();
            for (int i = 0; i < analysis.Properties.Length; i++)
            {
                var property = analysis.Properties[i];
                var wrapperType = GetPatternWrapperType(property);
                var propertyName = CapitalizeFirstLetter(property.PropertyName);

                sb.Append($"    {wrapperType} {propertyName} = default");

                if (i < analysis.Properties.Length - 1)
                {
                    sb.AppendLine(",");
                }
                else
                {
                    sb.AppendLine();
                }
            }
            sb.Append(")");
        }
        else
        {
            sb.Append(")");
        }

        sb.AppendLine($" : IPattern<{typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>, IPatternConstructor<{typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>");
        sb.AppendLine("{");

        // Evaluate method
        sb.AppendLine("    public MatchResult Evaluate(");
        sb.AppendLine($"        {typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} value,");
        sb.AppendLine("        string path = \"\")");
        sb.AppendLine("    {");

        if (analysis.Properties.Length > 0)
        {
            sb.AppendLine("        return MatchResult.Combine([");

            for (int i = 0; i < analysis.Properties.Length; i++)
            {
                var property = analysis.Properties[i];
                var propertyName = CapitalizeFirstLetter(property.PropertyName);
                var evaluation = GetPropertyEvaluation(property, propertyName);

                sb.Append($"            {evaluation}");

                if (i < analysis.Properties.Length - 1)
                {
                    sb.AppendLine(",");
                }
                else
                {
                    sb.AppendLine();
                }
            }

            sb.AppendLine("        ]);");
        }
        else
        {
            sb.AppendLine("        return new MatchResult.Success();");
        }

        sb.AppendLine("    }");

        // Add static From method
        sb.AppendLine();
        sb.AppendLine($"    public static IPattern<{typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}> From(");
        sb.AppendLine($"        {typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} value)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return ({patternName})value;");
        sb.AppendLine("    }");

        // Add static Create method (for IPatternConstructor)
        sb.AppendLine();
        sb.AppendLine($"    public static IPattern<{typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}> Create(");
        sb.AppendLine($"        {typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} value)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return ({patternName})value;");
        sb.AppendLine("    }");

        // Add implicit conversion operator
        sb.AppendLine();
        GenerateImplicitConversion(sb, typeSymbol, analysis.Properties);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetDefaultItemMatcherType(PropertyAnalysisResult property)
    {
        // If the element type requires a nested pattern, use the pattern type
        if (property.RequiresNestedPattern && property.NestedType != null)
        {
            var nestedFullName = property.NestedType.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat);
            return $"{nestedFullName}Pattern";
        }

        // For primitive elements, wrap in PatternDefault with ValuePattern
        return $"PatternDefault<{property.ElementType}, ValuePattern<{property.ElementType}>>";
    }

    private static string GetDictionaryValueMatcherType(PropertyAnalysisResult property)
    {
        // For dictionary values, determine the appropriate pattern type
        // This is the pattern type for the VALUE in Dictionary<K, V>

        // Check if value type is a nested pattern type
        if (property.RequiresNestedPattern && property.NestedType != null)
        {
            var nestedFullName = property.NestedType.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat);
            return $"{nestedFullName}Pattern";
        }

        // For primitive value types, use ValuePattern
        return $"ValuePattern<{property.ValueType}>";
    }

    private static string GetMatcherTypeForProperty(PropertyAnalysisResult property)
    {
        // For nested types with [AutoPattern], the pattern IS the matcher
        if (property.RequiresNestedPattern && property.NestedType != null)
        {
            var nestedFullName = property.NestedType.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat);
            return $"{nestedFullName}Pattern";
        }

        // For primitive/value types, use ValuePattern
        return $"ValuePattern<{property.PropertyType}>";
    }

    private static string GetPatternWrapperType(PropertyAnalysisResult property)
    {
        return property.WrapperKind switch
        {
            PatternWrapperKind.Value =>
                $"PatternDefault<{property.PropertyType}, {GetMatcherTypeForProperty(property)}>",

            PatternWrapperKind.Set =>
                // Use SetPatternDefault for unordered collections (HashSet, ISet)
                $"SetPatternDefault<{property.ElementType}, {GetDefaultItemMatcherType(property)}>",

            PatternWrapperKind.Sequence =>
                // Use SequencePatternDefault for ordered collections (arrays, lists)
                $"SequencePatternDefault<{property.ElementType}, {GetDefaultItemMatcherType(property)}>",

            PatternWrapperKind.Dictionary =>
                // Use DictionaryPatternDefault for proper dictionary matching
                $"DictionaryPatternDefault<{property.KeyType}, {property.ValueType}, {GetDictionaryValueMatcherType(property)}>",

            PatternWrapperKind.Nested =>
                // Wrap nested patterns in PatternDefault for consistency and null matching support
                // For nested types, the pattern type IS the matcher
                $"PatternDefault<{property.PropertyType}, {property.NestedType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}Pattern>",

            _ => throw new InvalidOperationException($"Unknown wrapper kind: {property.WrapperKind}")
        };
    }

    private static string GetPropertyEvaluation(PropertyAnalysisResult property, string propertyName)
    {
        var pathExpression = $"$\"{{path}}.{propertyName}\"";

        return property.WrapperKind switch
        {
            PatternWrapperKind.Value =>
                $"this.{propertyName}.Evaluate(value.{propertyName}, {pathExpression})",

            PatternWrapperKind.Set =>
                $"this.{propertyName}.Evaluate(value.{propertyName}, {pathExpression})",

            PatternWrapperKind.Sequence =>
                $"this.{propertyName}.Evaluate(value.{propertyName}, {pathExpression})",

            PatternWrapperKind.Dictionary =>
                $"this.{propertyName}.Evaluate(value.{propertyName}, {pathExpression})",

            PatternWrapperKind.Nested =>
                // Nested patterns now wrapped in PatternDefault, no null check needed
                $"this.{propertyName}.Evaluate(value.{propertyName}, {pathExpression})",

            _ => throw new InvalidOperationException($"Unknown wrapper kind: {property.WrapperKind}")
        };
    }

    private static string CapitalizeFirstLetter(string str)
    {
        if (string.IsNullOrEmpty(str))
            return str;

        return char.ToUpper(str[0]) + str.Substring(1);
    }

    private static void GenerateImplicitConversion(
        StringBuilder sb,
        INamedTypeSymbol typeSymbol,
        ImmutableArray<PropertyAnalysisResult> properties)
    {
        var typeName = typeSymbol.Name;
        var patternName = $"{typeName}Pattern";
        var typeFullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.AppendLine($"    public static implicit operator {patternName}(");
        sb.AppendLine($"        {typeFullName} value)");
        sb.AppendLine("    {");
        sb.Append($"        return new {patternName}(");

        if (properties.Length > 0)
        {
            sb.AppendLine();
            for (int i = 0; i < properties.Length; i++)
            {
                var property = properties[i];
                var propertyName = CapitalizeFirstLetter(property.PropertyName);
                var conversion = GetPropertyConversion(property, propertyName);

                sb.Append($"            {propertyName}: {conversion}");

                if (i < properties.Length - 1)
                {
                    sb.AppendLine(",");
                }
                else
                {
                    sb.AppendLine();
                }
            }
            sb.AppendLine("        );");
        }
        else
        {
            sb.AppendLine(");");
        }

        sb.AppendLine("    }");
    }

    private static string GetPropertyConversion(PropertyAnalysisResult property, string propertyName)
    {
        return property.WrapperKind switch
        {
            PatternWrapperKind.Value =>
                // PatternDefault<T, TPatternDefault> has implicit conversion from T
                $"value.{propertyName}",

            PatternWrapperKind.Set or PatternWrapperKind.Sequence =>
                // Convert collection to SequencePatternDefault
                GenerateCollectionConversion(property, propertyName),

            PatternWrapperKind.Dictionary =>
                // Use DictionaryPatternDefault.From for conversion
                GenerateDictionaryConversion(property, propertyName),

            PatternWrapperKind.Nested =>
                // PatternDefault<T, TPattern> has implicit conversion from T
                // The implicit conversion will call TPattern.From(value) automatically
                $"value.{propertyName}",

            _ => throw new InvalidOperationException($"Unknown wrapper kind: {property.WrapperKind}")
        };
    }

    private static string GenerateNestedConversion(PropertyAnalysisResult property, string propertyName)
    {
        if (property.NestedType == null)
        {
            return $"value.{propertyName}";
        }

        // Check if the nested type is a union (has UnionAttribute)
        var isUnion = property.NestedType.GetAttributes()
            .Any(a => a.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Contains("Dunet.UnionAttribute") ?? false);

        if (isUnion)
        {
            // For union types, we need to match on the value and convert each variant
            var unionFullName = property.NestedType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var variantTypes = property.NestedType.GetTypeMembers().Where(t => t.IsRecord).ToArray();

            if (variantTypes.Length == 0)
            {
                // No variants, shouldn't happen but handle gracefully
                return "default";
            }

            var matchCases = string.Join(", ", variantTypes.Select(v =>
            {
                var variantName = v.Name;
                var variantNameLower = char.ToLower(variantName[0]) + variantName.Substring(1);
                // Use implicit conversion from variant to variant pattern, then cast to base pattern
                return $"{variantNameLower} => ({unionFullName}Pattern)({unionFullName}Pattern.{variantName}){variantNameLower}";
            }));

            return $"value.{propertyName}.Match({matchCases})";
        }
        else
        {
            // For non-union nested patterns, use implicit conversion
            return $"value.{propertyName}";
        }
    }

    private static string GenerateCollectionConversion(PropertyAnalysisResult property, string propertyName)
    {
        var itemMatcherType = GetDefaultItemMatcherType(property);

        // Use the appropriate collection pattern type based on wrapper kind
        var patternType = property.WrapperKind == PatternWrapperKind.Set
            ? "SetPatternDefault"
            : "SequencePatternDefault";

        // Wrap the From result in a constructor to get the right type
        return $"new {patternType}<{property.ElementType}, {itemMatcherType}>({patternType}<{property.ElementType}, {itemMatcherType}>.From(value.{propertyName}))";
    }

    private static string GenerateDictionaryConversion(PropertyAnalysisResult property, string propertyName)
    {
        var valueMatcherType = GetDictionaryValueMatcherType(property);

        return $"new DictionaryPatternDefault<{property.KeyType}, {property.ValueType}, {valueMatcherType}>(DictionaryPatternDefault<{property.KeyType}, {property.ValueType}, {valueMatcherType}>.From(value.{propertyName}))";
    }

    private static void GenerateVariantImplicitConversion(
        StringBuilder sb,
        VariantAnalysisResult variant,
        string variantFullType,
        string variantName)
    {
        var patternName = $"{variantName}";

        sb.AppendLine($"        public static implicit operator {patternName}(");
        sb.AppendLine($"            {variantFullType} value)");
        sb.AppendLine("        {");
        sb.Append($"            return new {patternName}(");

        if (variant.Properties.Length > 0)
        {
            sb.AppendLine();
            for (int i = 0; i < variant.Properties.Length; i++)
            {
                var property = variant.Properties[i];
                var propertyName = CapitalizeFirstLetter(property.PropertyName);
                var conversion = GetPropertyConversion(property, propertyName);

                sb.Append($"                {propertyName}: {conversion}");

                if (i < variant.Properties.Length - 1)
                {
                    sb.AppendLine(",");
                }
                else
                {
                    sb.AppendLine();
                }
            }
            sb.AppendLine("            );");
        }
        else
        {
            sb.AppendLine(");");
        }

        sb.AppendLine("        }");
    }

    private static string GenerateUnionPattern(TypeAnalysisResult analysis)
    {
        var typeSymbol = analysis.TypeSymbol;
        var typeName = typeSymbol.Name;
        var patternName = $"{typeName}Pattern";
        var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
        var isGlobalNamespace = typeSymbol.ContainingNamespace.IsGlobalNamespace;

        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using PotternMotching;");
        sb.AppendLine("using PotternMotching.Patterns;");
        sb.AppendLine("using Dunet;");
        sb.AppendLine();

        // Namespace (only if not global)
        if (!isGlobalNamespace)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        // Union pattern class declaration - abstract base with no parameters
        var unionFullType = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.AppendLine($"public abstract partial record {patternName} : IPattern<{unionFullType}>, IPatternConstructor<{unionFullType}>");
        sb.AppendLine("{");
        sb.AppendLine($"    private {patternName}() {{ }}");
        sb.AppendLine();

        // Generate the abstract Evaluate method for the union pattern
        sb.AppendLine("    public abstract MatchResult Evaluate(");
        sb.AppendLine($"        {unionFullType} value,");
        sb.AppendLine("        string path = \"\");");
        sb.AppendLine();

        // Add static From method for union pattern
        sb.AppendLine($"    public static IPattern<{unionFullType}> From(");
        sb.AppendLine($"        {unionFullType} value)");
        sb.AppendLine("    {");
        sb.AppendLine("        return value.Match(");

        for (int i = 0; i < analysis.Variants.Length; i++)
        {
            var variant = analysis.Variants[i];
            var variantNameLower = char.ToLower(variant.VariantName[0]) + variant.VariantName.Substring(1);

            sb.Append($"            {variantNameLower} => ({patternName})({patternName}.{variant.VariantName}){variantNameLower}");

            if (i < analysis.Variants.Length - 1)
            {
                sb.AppendLine(",");
            }
            else
            {
                sb.AppendLine();
            }
        }

        sb.AppendLine("        );");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Add static Create method for union pattern (IPatternConstructor interface)
        sb.AppendLine($"    public static IPattern<{unionFullType}> Create(");
        sb.AppendLine($"        {unionFullType} value)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return From(value);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate each variant pattern
        foreach (var variant in analysis.Variants)
        {
            sb.AppendLine();
            GenerateVariantPattern(sb, variant, typeSymbol);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateUnionEvaluateMethod(StringBuilder sb, TypeAnalysisResult analysis)
    {
        var typeSymbol = analysis.TypeSymbol;

        sb.AppendLine("    public MatchResult Evaluate(");
        sb.AppendLine($"        {typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} value,");
        sb.AppendLine("        string path = \"\")");
        sb.AppendLine("    {");
        sb.AppendLine("        return this.Match(");

        for (int i = 0; i < analysis.Variants.Length; i++)
        {
            var variant = analysis.Variants[i];
            var variantNameLower = char.ToLower(variant.VariantName[0]) + variant.VariantName.Substring(1);
            var variantValueName = "value" + variant.VariantName;

            sb.Append($"            {variantNameLower} => value.Match(");

            // Generate match arms for this variant
            for (int j = 0; j < analysis.Variants.Length; j++)
            {
                var otherVariant = analysis.Variants[j];
                var otherVariantNameLower = char.ToLower(otherVariant.VariantName[0]) + otherVariant.VariantName.Substring(1);

                if (j > 0)
                    sb.Append(", ");

                if (i == j)
                {
                    // This is the matching variant - evaluate it
                    sb.Append($"{variantValueName} => {variantNameLower}.Evaluate({variantValueName}, path)");
                }
                else
                {
                    // This is a mismatched variant - return failure
                    sb.Append($"_ => new MatchResult.Failure([$\"{{path}}: Expected variant {variant.VariantName} but got {otherVariant.VariantName}\"])");
                }
            }

            sb.Append(")");

            if (i < analysis.Variants.Length - 1)
            {
                sb.AppendLine(",");
            }
            else
            {
                sb.AppendLine();
            }
        }

        sb.AppendLine("        );");
        sb.AppendLine("    }");
    }

    private static void GenerateVariantPattern(
        StringBuilder sb,
        VariantAnalysisResult variant,
        INamedTypeSymbol unionSymbol)
    {
        var variantName = variant.VariantName;
        var variantFullType = $"{unionSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}.{variantName}";
        var unionFullType = unionSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var patternName = $"{unionSymbol.Name}Pattern";

        // Variant pattern class declaration - sealed, inherits from parent, implements IPattern<Variant>
        sb.Append($"    public sealed partial record {variantName}(");

        // Parameters
        if (variant.Properties.Length > 0)
        {
            sb.AppendLine();
            for (int i = 0; i < variant.Properties.Length; i++)
            {
                var property = variant.Properties[i];
                var wrapperType = GetPatternWrapperType(property);
                var propertyName = CapitalizeFirstLetter(property.PropertyName);

                sb.Append($"        {wrapperType} {propertyName} = default");

                if (i < variant.Properties.Length - 1)
                {
                    sb.AppendLine(",");
                }
                else
                {
                    sb.AppendLine();
                }
            }
            sb.Append("    )");
        }
        else
        {
            sb.Append(")");
        }

        sb.AppendLine($" : {patternName}, IPattern<{variantFullType}>");
        sb.AppendLine("    {");

        // Evaluate method for specific variant type
        sb.AppendLine("        public MatchResult Evaluate(");
        sb.AppendLine($"            {variantFullType} value,");
        sb.AppendLine("            string path = \"\")");
        sb.AppendLine("        {");

        if (variant.Properties.Length > 0)
        {
            sb.AppendLine("            return MatchResult.Combine([");

            for (int i = 0; i < variant.Properties.Length; i++)
            {
                var property = variant.Properties[i];
                var propertyName = CapitalizeFirstLetter(property.PropertyName);
                var evaluation = GetPropertyEvaluation(property, propertyName);

                sb.Append($"                {evaluation}");

                if (i < variant.Properties.Length - 1)
                {
                    sb.AppendLine(",");
                }
                else
                {
                    sb.AppendLine();
                }
            }

            sb.AppendLine("            ]);");
        }
        else
        {
            sb.AppendLine("            return new MatchResult.Success();");
        }

        sb.AppendLine("        }");
        sb.AppendLine();

        // Override Evaluate method for union type - checks variant and delegates
        var variantNameLower = char.ToLower(variantName[0]) + variantName.Substring(1);
        sb.AppendLine($"        public override MatchResult Evaluate(");
        sb.AppendLine($"            {unionFullType} value,");
        sb.AppendLine("            string path = \"\")");
        sb.AppendLine("        {");
        sb.AppendLine($"            return value is {variantFullType} {variantNameLower}");
        sb.AppendLine($"                ? this.Evaluate({variantNameLower}, path)");
        sb.AppendLine($"                : new MatchResult.Failure([$\"{{path}}: Expected variant {variantName}\"]);");
        sb.AppendLine("        }");

        // Add static From method for variant
        sb.AppendLine();
        sb.AppendLine($"        public static IPattern<{variantFullType}> From(");
        sb.AppendLine($"            {variantFullType} value)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return ({variantName})value;");
        sb.AppendLine("        }");

        // Add implicit conversion operator for variant
        sb.AppendLine();
        GenerateVariantImplicitConversion(sb, variant, variantFullType, variantName);

        sb.AppendLine("    }");
    }
}
