namespace PotternMotching.SourceGen;

using System.Text;
using Microsoft.CodeAnalysis;
using PotternMotching.SourceGen.Models;

internal static class PatternCodeGenerator
{
    public static string Generate(TypeAnalysisResult analysis)
    {
        var typeSymbol = analysis.TypeSymbol;
        var typeName = typeSymbol.Name;
        var patternName = $"{typeName}Pattern";
        var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();
        var isGlobalNamespace = typeSymbol.ContainingNamespace.IsGlobalNamespace;

        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using PotternMotching;");
        sb.AppendLine("using PotternMotching.Patterns;");
        sb.AppendLine("using PotternMotching.Matchers;");
        sb.AppendLine();

        // Namespace (only if not global)
        if (!isGlobalNamespace)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        // Class declaration
        sb.Append($"public sealed record {patternName}(");

        // Parameters
        if (analysis.Properties.Length > 0)
        {
            sb.AppendLine();
            for (int i = 0; i < analysis.Properties.Length; i++)
            {
                var property = analysis.Properties[i];
                var wrapperType = GetPatternWrapperType(property);
                var propertyName = CapitalizeFirstLetter(property.PropertyName);

                sb.Append($"    {wrapperType} {propertyName} = default");

                if (i < analysis.Properties.Length - 1)
                {
                    sb.AppendLine(",");
                }
                else
                {
                    sb.AppendLine();
                }
            }
            sb.Append(")");
        }
        else
        {
            sb.Append(")");
        }

        sb.AppendLine($" : IMatcher<{typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>");
        sb.AppendLine("{");

        // Evaluate method
        sb.AppendLine("    public MatchResult Evaluate(");
        sb.AppendLine($"        {typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} value,");
        sb.AppendLine("        string path = \"\")");
        sb.AppendLine("    {");

        if (analysis.Properties.Length > 0)
        {
            sb.AppendLine("        return MatchResult.Combine([");

            for (int i = 0; i < analysis.Properties.Length; i++)
            {
                var property = analysis.Properties[i];
                var propertyName = CapitalizeFirstLetter(property.PropertyName);
                var evaluation = GetPropertyEvaluation(property, propertyName);

                sb.Append($"            {evaluation}");

                if (i < analysis.Properties.Length - 1)
                {
                    sb.AppendLine(",");
                }
                else
                {
                    sb.AppendLine();
                }
            }

            sb.AppendLine("        ]);");
        }
        else
        {
            sb.AppendLine("        return new MatchResult.Success();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetPatternWrapperType(PropertyAnalysisResult property)
    {
        return property.WrapperKind switch
        {
            PatternWrapperKind.Value =>
                $"ValuePattern<{property.PropertyType}>",

            PatternWrapperKind.Set =>
                $"SetPattern<{property.ElementType}>",

            PatternWrapperKind.Sequence when property.RequiresNestedPattern =>
                $"SequencePattern<{property.ElementType}, {property.NestedType!.Name}Pattern>",

            PatternWrapperKind.Sequence =>
                $"SequencePattern<{property.ElementType}, IMatcher<{property.ElementType}>>",

            PatternWrapperKind.Dictionary =>
                $"DictionaryPattern<{property.KeyType}, {property.ValueType}>",

            PatternWrapperKind.Nested =>
                $"{property.NestedType!.Name}Pattern?",

            _ => throw new InvalidOperationException($"Unknown wrapper kind: {property.WrapperKind}")
        };
    }

    private static string GetPropertyEvaluation(PropertyAnalysisResult property, string propertyName)
    {
        var pathExpression = $"$\"{{path}}.{propertyName}\"";

        return property.WrapperKind switch
        {
            PatternWrapperKind.Value =>
                $"this.{propertyName}.Value?.Evaluate(value.{propertyName}, {pathExpression}) ?? new MatchResult.Success()",

            PatternWrapperKind.Set =>
                $"this.{propertyName}.Values?.Evaluate(value.{propertyName}, {pathExpression}) ?? new MatchResult.Success()",

            PatternWrapperKind.Sequence =>
                $"this.{propertyName}.Values?.Evaluate(value.{propertyName}, {pathExpression}) ?? new MatchResult.Success()",

            PatternWrapperKind.Dictionary =>
                $"this.{propertyName}.Values?.Evaluate(value.{propertyName}, {pathExpression}) ?? new MatchResult.Success()",

            PatternWrapperKind.Nested =>
                $"this.{propertyName}?.Evaluate(value.{propertyName}, {pathExpression}) ?? new MatchResult.Success()",

            _ => throw new InvalidOperationException($"Unknown wrapper kind: {property.WrapperKind}")
        };
    }

    private static string CapitalizeFirstLetter(string str)
    {
        if (string.IsNullOrEmpty(str))
            return str;

        return char.ToUpper(str[0]) + str.Substring(1);
    }
}
